name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test Commands
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go > 1.13
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Install Node dependencies
      run: |
          sudo apt update
          sudo apt install lm-sensors build-essential -y

    - name: Build
      run: make

    - name: Test CI
      run: make test_ci

    - name: Coverage
      run: make cover

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: pada-apps
          path: bin/
